// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn1k7OolvW60jTsQq4YN01IDGphIxntRA',
    appId: '1:354622519459:android:e66dc211b5af79c231a716',
    messagingSenderId: '354622519459',
    projectId: 'bloodmate-6d726',
    storageBucket: 'bloodmate-6d726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlfjjqM-7Hdg66uX0F4l2x0W3R-STHrU',
    appId: '1:354622519459:ios:b9e25f697d74c76931a716',
    messagingSenderId: '354622519459',
    projectId: 'bloodmate-6d726',
    storageBucket: 'bloodmate-6d726.firebasestorage.app',
    androidClientId: '354622519459-hruj1mfakbsd2d02j7m3hoki2m0403vs.apps.googleusercontent.com',
    iosClientId: '354622519459-tmfesp9s3hbepvvgfhci6udesnssgjc9.apps.googleusercontent.com',
    iosBundleId: 'com.amtzo.bloodDonation',
  );
}
